### ISSUE TITLE
Installation problem on Ubuntu 20.04

### ISSUE THREAD

**Issue by adamnfish** [dmtrKovalenko/odiff#11]
After performing `npm install odiff-bin` without errors, the library cannot be imported:

```
Error: Cannot find module 'odiff-bin'
Require stack:
- ~/dev/project-dir/src/project.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (~/dev/project-dir/src/project.js:1:21)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  code: 'MODULE_NOT_FOUND',
```

Attempting to run the binary directly from `node_modules` reveals the following error:

```
~/dev/project-dir/node_modules/odiff-bin/3_________________/i/odiff-b684a0b4/bin/ODiffBin: error while loading shared libraries: libpng12.so.0: cannot open shared object file: No such file or directory
```

I notice the windows instructions mention that `libpng` needs to be separately installed, is the same true on Linux? There doesn't appear to be a great candidate for a package in the standard Ubuntu repositories that will fix this missing dependency, is there something I'm missing?

Thanks very much.

**Comment by dmtrKovalenko** [comment]
We are using plain Ubuntu docker image to test the project. And there is no error at all. Can you please make a reproduction that can be run in docker or vm? 

Thank you 🙏

**Comment by viraxslot** [comment]
@dmtrKovalenko I have the same problem on MacOS 10.15.7
Code is pretty simple:
```javascript
import { compare } from 'odiff-bin';

const referencePath = './screenshots/file1.png';
const currentImagePath = './screenshots/file2.png';
const diffPath = './screenshots/diff.png';

const result = compare(referencePath, currentImagePath, diffPath);
console.log(result);
```

I run it like
```
npx ts-node test/e2e/visual/test.ts 
Cannot find module 'odiff-bin'
```

```
npx odiff --help
npx: installed 1 in 2.198s
command not found: odiff

ls -lah node_modules/odiff-bin/
total 18552
drwxr-xr-x   16 viraxslot  staff   512B  9 Dec 23:39 .
drwxr-xr-x  418 viraxslot  staff    13K  9 Dec 23:39 ..
drwxr-xr-x    5 viraxslot  staff   160B  9 Dec 23:39 3______
-rw-r--r--    1 viraxslot  staff   1.0K 26 Oct  1985 LICENSE
-rw-r--r--    1 viraxslot  staff   5.8K 26 Oct  1985 README.md
drwxr-xr-x    3 viraxslot  staff    96B  9 Dec 23:39 _export
drwxr-xr-x    4 viraxslot  staff   128B  9 Dec 23:39 bin
-rwxrwxrwx    1 viraxslot  staff   421K  9 Dec 23:39 esyInstallRelease.js
-rw-r--r--    1 viraxslot  staff   8.6M 26 Oct  1985 odiff-1.0.0.tgz
-rw-r--r--    1 viraxslot  staff   507B 26 Oct  1985 odiff.d.ts
-rw-r--r--    1 viraxslot  staff   2.1K 26 Oct  1985 odiff.js
-rw-r--r--    1 viraxslot  staff   1.2K  9 Dec 23:39 package.json
drwxr-xr-x    8 viraxslot  staff   256B  9 Dec 23:39 platform-darwin
drwxr-xr-x    8 viraxslot  staff   256B  9 Dec 23:39 platform-linux
drwxr-xr-x    8 viraxslot  staff   256B  9 Dec 23:39 platform-windows-x64
-rw-r--r--    1 viraxslot  staff   4.6K 26 Oct  1985 postinstall.js
```

```
node -v
v12.18.3
```

**Comment by viraxslot** [comment]
@dmtrKovalenko here is an example with docker image https://github.com/viraxslot/odiff-test

**Comment by viraxslot** [comment]
@dmtrKovalenko I've updated odiff-bin to 1.0.4 version and now it works locally.
But it still doesn't work in Docker

Please check the new commit
https://github.com/viraxslot/odiff-test

And the result
```
npm run start

> odiff-test@1.0.0 start /Users/viraxslot/Documents/projects/odiff-test
> docker container run odiff-test

Run entrypoint
(node:8) UnhandledPromiseRejectionWarning: Error: /home/odiff/node_modules/odiff-bin/bin/ODiffBin: 1: /home/odiff/node_modules/odiff-bin/bin/ODiffBin: Syntax error: word unexpected (expecting ")")

    at ChildProcess.<anonymous> (/home/odiff/node_modules/odiff-bin/odiff.js:81:13)
    at ChildProcess.emit (events.js:326:22)
    at ChildProcess.EventEmitter.emit (domain.js:483:12)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:314:20)
    at Socket.EventEmitter.emit (domain.js:483:12)
    at Pipe.<anonymous> (net.js:676:12)
(node:8) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:8) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by viraxslot** [comment]
@adamnfish hi, finally it works for me with such Docker image:
```
FROM mcr.microsoft.com/playwright:v1.7.0-focal
USER root
RUN mkdir -p /home/tests
WORKDIR /home/tests

RUN apt-get install -y software-properties-common && add-apt-repository ppa:linuxuprising/libpng12 && apt-get update
RUN apt-get install -y libpng12-0
...
```
You're right, due to [this article ](https://www.linuxuprising.com/2018/05/fix-libpng12-0-missing-in-ubuntu-1804.html) there is no `libpng` dependency preinstalled in Ubuntu.
Hope it'll help.

**Comment by dmtrKovalenko** [comment]
Really, we are using ubuntu 16 image, which has this dependency – I`ll update the docs to include required
