### ISSUE TITLE
odiff-bin. TypeError: odiff: option `--antialiasing' is a flag, it cannot take the argument `true'

### ISSUE THREAD

**Issue by pashidlos** [dmtrKovalenko/odiff#44]
```js
(async () => {
  const result = await odiff.compare(
    getImagePath("1.png"),
    getImagePath("diffLayout2.png"),
    getImagePath("diff.png"),
    {
      antialiasing: true
    }
  );

  console.log(result);
})();
```
```
(node:74741) UnhandledPromiseRejectionWarning: TypeError: odiff: option `--antialiasing' is a flag, it cannot take the argument `true'

    at ChildProcess.<anonymous> (.../node_modules/odiff-bin/odiff.js:123:13)
    at ChildProcess.emit (events.js:327:22)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:674:12)
```

**Comment by eWert-Online** [comment]
Thank you for finding and reporting all of these errors! 
That was my mistake. I will see, if I can fix this today.

@dmtrKovalenko 
Its probably a good idea to also add a test for this case.
I will see, if any other node bindings are not tested and add a test for all of them.
