### ISSUE TITLE
Linux alpine. Can't compare images - empty error 

### ISSUE THREAD

**Issue by pashidlos** [dmtrKovalenko/odiff#55]
docker image `node:12.18.4-alpine`
odiff-bin `2.4.1`

```
api_1        | [Nest] 25   - 07/15/2021, 3:59:59 PM   Object:
api_1        | {}
api_1        |  +31481ms
api_1        | Error
api_1        |     at ChildProcess.<anonymous> (/node_modules/odiff-bin/odiff.js:134:13)
api_1        |     at ChildProcess.emit (events.js:327:22)
api_1        |     at maybeClose (internal/child_process.js:1021:16)
api_1        |     at Socket.<anonymous> (internal/child_process.js:443:11)
api_1        |     at Socket.emit (events.js:315:20)
api_1        |     at Pipe.<anonymous> (net.js:674:12)
```

**Comment by Klaster1** [comment]
For those with the same issue, using a Debian-based node image instead of an Alpine-based was a reasonable workaround. I'd at least mention the compatibility issue in the readme so people know about this beforehand.

**Comment by Gogibahp** [comment]
Not sure if this entirely solves the issue but I was able to get odiff running on alpine by installing glib in the image.

```
RUN apk update && \
    apk add --no-cache bash curl

RUN apk add --no-cache \
    libc6-compat
```
Afterwards I just copied the odiff linux binary into my docker image and ran chmod to make sure that the binary could be executed.
