### ISSUE TITLE
question how to use your tool with Cypress/Typescript

### ISSUE THREAD

**Issue by jradom** [dmtrKovalenko/odiff#6]
Hello,

I saw your sample images use Cypress screenshots.  So, do you have by any chance a sample code with Cypress with necessary configurations?

Thanks

Jeff

**Comment by dmtrKovalenko** [comment]
Thank you @jradom – I will make an example! Thanks

**Comment by jradom** [comment]
sounds great

Thanks (spasibo)

Jeff

**Comment by jradom** [comment]
Hi Dmitriy,

I've tried CLI odiff run and got this

radomj-N7JG5L:~ radomj$ odiff --help

-bash: odiff: command not found



Please advise.


Thanks


Jeff

**Comment by jradom** [comment]
I was able to run your tool like this under no_modules


but got these errors

SyntaxError: Invalid or unexpected token
    at Module._compile (internal/modules/cjs/loader.js:895:18)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11
radomj-N7JG5L:bin radomj$ node ODiffBin ~/Downloads/case_baseline.png ~/Downloads/case_actual.png  ~/Downloads/case_diff.png

**Comment by jradom** [comment]
I'd also like to know if I run CLI from Typescript or Cypress if I'll get a return code 0 or 1 when images are identical or mismatched

**Comment by jradom** [comment]
Hi Dmitry,

This is just a friendly reminder about Cypress/Typescript sample code you
had promised.  I really like your tool but need to try it before use.
Also, I pretty new to Cypress and Typescript/javascript but use
java/Selenium for about 10 years

Thanks

Jeff

**Comment by dmtrKovalenko** [comment]
Sorry, I’ve been working on integrating this with other more complex snapshot-based stuff. But ok I will do a quick demo

**Comment by jradom** [comment]
this sounds really great because I was able to use your tool at all but in readme ,   it had looked  really great

Thanks a lot in advance

Jeff

**Comment by jradom** [comment]
BTW, where in Ukraine are you located?  Just curious

**Comment by georgio1972** [comment]
> Hello,
> 
> I saw your sample images use Cypress screenshots. So, do you have by any chance a sample code with Cypress with necessary configurations?
> 
> Thanks
> 
> Jeff

Hello Jeff, were you able to make this work in Cypess? I have been trying but since I am pretty new to Cypress/Typescript I don't really know how to configure it correctly. Thanks

**Comment by dhamo-pk** [comment]
Hi @dmtrKovalenko,
odiff looks promising., could you add some more details on how to integrate with cypress? Maybe an example repo would be a great help.

**Comment by sadeesh-sdet** [comment]
Hi everyone, Please check this [detailed blog post](https://glebbahmutov.com/blog/canvas-testing/#visual-test-using-odiff) from [@gleb](https://twitter.com/bahmutov) about odiff and cypress integration and here is the [repo](https://github.com/bahmutov/monalego) for the same.
